mylist = """making-moves
digit-manipulation
digit-manipulation
integer-equation
integer-equation
digit-manipulation
integer-equation
integer-equation
game
sequence-properties
digit-manipulation
integer-equation
game
integer-equation
integer-equation
integer-equation
digit-manipulation
proving-inequality
cryptarithm
digit-manipulation
digit-manipulation
proving-inequality
integer-equation
digit-manipulation
magic-configuration
prove-inequality
game
magic-configuration
cryptarithm
word-problem
fill-in-table
procedure
integer-equation
digit-manipulation
sequence-properties
digit-manipulation
integer-equation
integer-geometry
integer-equation
game
integer-equation
digit-manipulation
functional-equation
string-counting
decimal-manipulation
optimization
prove-inequality
digit-manipulation
magic-configuration
cryptarithm
build-expression
integer-geometry
digit-manipulation
procedure
fill-in-table
digit-manipulation
word-problem
integer-equation
digit-manipulation
digit-manipulation
digit-manipulation
fill-in-table
word-problem
digit-manipulation
word-problem
string-counting
procedure
word-problem
word-problem
digit-manipulation
word-problem
digit-manipulation
word-problem
fill-in-table
fill-in-table
string-counting
string-counting
word-problem
digit-manipulation
digit-manipulation
digit-manipulation
digit-manipulation
digit-manipulation
digit-manipulation
cryptarithm
integer-equation
cryptarithm
word-problem
digit-manipulation
optimization
integer-equation
integer-equation
digit-manipulation
integer-equation
integer-equation
integer-equation
optimization
integer-equation
fill-in-table
digit-manipulation
special-numbers
fill-in-table
integer-equation
integer-equation
integer-equation
integer-equation
system-of-equations
special-numbers
comparison
digit-manipulation
special-numbers
integer-equation
making-moves
game
integer-equation
integer-equation
game
special-numbers
special-numbers
special-numbers
optimization
construction
construction
digit-manipulation
game
optimization
digit-manipulation
game
making-moves
optimization
digit-manipulation
making-moves
optimization
construction
special-numbers,sum-of-digits
optimization
game
digit-manipulation
fill-in-table
making-moves
word-problem
construction
construction
magic-configuration
digit-manipulation
special-numbers
making-moves
magic-configuration
fill-in-table
fill-in-table
digit-manipulation
optimization
games
integer-equation
game
making-moves
digit-manipulation
integer-equation
integer-equation
integer-equation
integer-equation
optimization
digit-manipulation
integer-equation
""".split()
# Remove duplicates
unique_list = list(set(mylist))

# Sort the list alphabetically
unique_list.sort()

# Print each unique element on a new line
for item in unique_list:
    print(item)
