{
    items: [

{
            type: "Video",
            label: "amo38-g05-p01",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2011",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "integer-factorization",
            YTurl: "https://www.youtube.com/watch?v=tWx-UGFeuSA",
			vurl: "amo38-g05-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/tWx-UGFeuSA/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "38.AMO, 5.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo38-g05-p02",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2011",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "integer-factorization",
            YTurl: "https://www.youtube.com/watch?v=tcAc6S9-VlE",
			vurl: "amo38-g05-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/tcAc6S9-VlE/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "38.AMO, 5.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo38-g05-p03",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2011",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "small-increment",
            YTurl: "https://www.youtube.com/watch?v=ZXMm0a2NE9c",
			vurl: "amo38-g05-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/ZXMm0a2NE9c/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "38.AMO, 5.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo38-g05-p04",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2011",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "graph-properties",
            YTurl: "https://www.youtube.com/watch?v=qZ3xYhXjkuA",
			vurl: "amo38-g05-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/qZ3xYhXjkuA/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "38.AMO, 5.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo38-g05-p05",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2011",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "symmetry",
            YTurl: "https://www.youtube.com/watch?v=ynAOj1ip2wM",
			vurl: "amo38-g05-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/ynAOj1ip2wM/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "38.AMO, 5.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g05-p01",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "modular-arithmetic",
            YTurl: "https://www.youtube.com/watch?v=RX4BrGMvxDc",
			vurl: "amo39-g05-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/RX4BrGMvxDc/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 5.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },



{
            type: "Video",
            label: "amo39-g05-p03",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "worst-case-scenario",
            YTurl: "https://www.youtube.com/watch?v=b-rJQuY5gO8",
			vurl: "amo39-g05-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/b-rJQuY5gO8/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 5.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g05-p04",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "graph-properties",
            YTurl: "https://www.youtube.com/watch?v=AgHNxnHjFGY",
			vurl: "amo39-g05-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/AgHNxnHjFGY/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 5.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g09-p01",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "integer-factorization",
            YTurl: "https://www.youtube.com/watch?v=ZnSvxqDyNuk",
			vurl: "amo39-g09-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/ZnSvxqDyNuk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 9.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g09-p02",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "graph-properties",
            YTurl: "https://www.youtube.com/watch?v=7PDaCUVFnbw",
			vurl: "amo39-g09-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/7PDaCUVFnbw/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 9.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g09-p03",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "graph-properties",
            YTurl: "https://www.youtube.com/watch?v=WV3oMgrKvaQ",
			vurl: "amo39-g09-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/WV3oMgrKvaQ/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 9.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g09-p04",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "invariants",
            YTurl: "https://www.youtube.com/watch?v=gKwJyRVBxk8",
			vurl: "amo39-g09-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/gKwJyRVBxk8/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 9.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo39-g09-p05",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2012",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "extreme-element",
            YTurl: "https://www.youtube.com/watch?v=eE3-qUmyW74",
			vurl: "amo39-g09-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/eE3-qUmyW74/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "39.AMO, 9.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g05-p01",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "case-analysis",
            YTurl: "https://www.youtube.com/watch?v=UNyM7DyFDug",
			vurl: "amo40-g05-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/UNyM7DyFDug/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 5.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g05-p02",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "directed-graph",
            YTurl: "https://www.youtube.com/watch?v=96mCTGXI4N4",
			vurl: "amo40-g05-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/96mCTGXI4N4/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 5.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g05-p03",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "adding-with-regrouping",
            YTurl: "https://www.youtube.com/watch?v=7o9b9yKO08c",
			vurl: "amo40-g05-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/7o9b9yKO08c/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 5.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g05-p04",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "trial-and-error",
            YTurl: "https://www.youtube.com/watch?v=aPtiwtx9Jkg",
			vurl: "amo40-g05-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/aPtiwtx9Jkg/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 5.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g05-p05",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "pigeonhole-principle",
            YTurl: "https://www.youtube.com/watch?v=YQAQ3e3cfqo",
			vurl: "amo40-g05-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/YQAQ3e3cfqo/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 5.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g06-p01",   
            form: "Grade6-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "commutativity-associativity",
            YTurl: "https://www.youtube.com/watch?v=VAqkROCPuKk",
			vurl: "amo40-g06-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/VAqkROCPuKk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 6.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g06-p02",   
            form: "Grade6-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "divisibility-rule",
            YTurl: "https://www.youtube.com/watch?v=OSqW4Go6wDU",
			vurl: "amo40-g06-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/OSqW4Go6wDU/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 6.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g06-p03",   
            form: "Grade6-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "trial-and-error",
            YTurl: "https://www.youtube.com/watch?v=-aJm0RGdE10",
			vurl: "amo40-g06-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/-aJm0RGdE10/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 6.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g06-p04",   
            form: "Grade6-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "perfect-square",
            YTurl: "https://www.youtube.com/watch?v=4Dj_iLs917Y",
			vurl: "amo40-g06-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/4Dj_iLs917Y/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 6.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g06-p05",   
            form: "Grade6-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "combinatorial-game",
            YTurl: "https://www.youtube.com/watch?v=svul9-D_5i0",
			vurl: "amo40-g06-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/svul9-D_5i0/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 6.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g07-p01",   
            form: "Grade7-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "algebraic-inequality",
            YTurl: "https://www.youtube.com/watch?v=vxpifqi6pO4",
			vurl: "amo40-g07-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/vxpifqi6pO4/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 7.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g07-p02",   
            form: "Grade7-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "triangle-inequality",
            YTurl: "https://www.youtube.com/watch?v=HXFdhK5xN9M",
			vurl: "amo40-g07-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/HXFdhK5xN9M/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 7.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g07-p03",   
            form: "Grade7-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "perfect-square",
            YTurl: "https://www.youtube.com/watch?v=OcYOH2-crnk",
			vurl: "amo40-g07-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/OcYOH2-crnk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 7.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g07-p04",   
            form: "Grade7-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "trial-and-error",
            YTurl: "https://www.youtube.com/watch?v=vNAo5sk7KjA",
			vurl: "amo40-g07-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/vNAo5sk7KjA/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 7.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g07-p05",   
            form: "Grade7-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "combinatorial-game",
            YTurl: "https://www.youtube.com/watch?v=IG5MsMdt7oU",
			vurl: "amo40-g07-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/IG5MsMdt7oU/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 7.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g08-p01",   
            form: "Grade8-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "integer-equation",
            YTurl: "https://www.youtube.com/watch?v=Jb2vhUIYHFU",
			vurl: "amo40-g08-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/Jb2vhUIYHFU/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 8.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g08-p02",   
            form: "Grade8-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "triangle-inequality",
            YTurl: "https://www.youtube.com/watch?v=cXmlpA3LJAc",
			vurl: "amo40-g08-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/cXmlpA3LJAc/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 8.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g08-p03",   
            form: "Grade8-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "quadratic-equation",
            YTurl: "https://www.youtube.com/watch?v=mcbQM4F-SFg",
			vurl: "amo40-g08-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/mcbQM4F-SFg/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 8.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g08-p04",   
            form: "Grade8-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "using-symmetry",
            YTurl: "https://www.youtube.com/watch?v=Cvqr2NmFX94",
			vurl: "amo40-g08-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/Cvqr2NmFX94/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 8.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g08-p05",   
            form: "Grade8-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "exhaustive-searchr",
            YTurl: "https://www.youtube.com/watch?v=j6PdM7lk7Sg",
			vurl: "amo40-g08-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/j6PdM7lk7Sg/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 8.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },



{
            type: "Video",
            label: "amo40-g09-p02",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "proof-by-contradiction",
            YTurl: "https://www.youtube.com/watch?v=sWhEMTTHCkw",
			vurl: "amo40-g09-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/sWhEMTTHCkw/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 9.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g09-p03",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "decimal-representation",
            YTurl: "https://www.youtube.com/watch?v=1y0f2s8MimI",
			vurl: "amo40-g09-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/1y0f2s8MimI/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 9.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g09-p04",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "squaring",
            YTurl: "https://www.youtube.com/watch?v=SFmo2aeTFT0",
			vurl: "amo40-g09-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/SFmo2aeTFT0/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 9.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g09-p05",   
            form: "Grade9-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "inscribed-angles",
            YTurl: "https://www.youtube.com/watch?v=ueXWH7a_hmA",
			vurl: "amo40-g09-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/ueXWH7a_hmA/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 9.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g10-p01",   
            form: "Grade10-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "continuity",
            YTurl: "https://www.youtube.com/watch?v=zgtN_jL_4Ks",
			vurl: "amo40-g10-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/zgtN_jL_4Ks/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 10.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g10-p02",   
            form: "Grade10-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "inscribed-angles",
            YTurl: "https://www.youtube.com/watch?v=25fEje8cBsk",
			vurl: "amo40-g10-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/25fEje8cBsk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 10.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g10-p03",   
            form: "Grade10-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "case-analysis",
            YTurl: "https://www.youtube.com/watch?v=SpM9lx1dtGA",
			vurl: "amo40-g10-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/SpM9lx1dtGA/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 10.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g10-p04",   
            form: "Grade10-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "pigeonhole-principle",
            YTurl: "https://www.youtube.com/watch?v=0URgsDdpP-A",
			vurl: "amo40-g10-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/0URgsDdpP-A/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 10.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g10-p05",   
            form: "Grade10-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "even-odd-numbers",
            YTurl: "https://www.youtube.com/watch?v=CiiboXnTWS0",
			vurl: "amo40-g10-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/CiiboXnTWS0/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 10.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g11-p01",   
            form: "Grade11-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "modular-arithmetic",
            YTurl: "https://www.youtube.com/watch?v=luIp4XRAFLk",
			vurl: "amo40-g11-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/luIp4XRAFLk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 11.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g11-p02",   
            form: "Grade11-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "trigonometry",
            YTurl: "https://www.youtube.com/watch?v=5Ir-ExKzdYU",
			vurl: "amo40-g11-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/5Ir-ExKzdYU/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 11.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g11-p03",   
            form: "Grade11-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "sequences",
            YTurl: "https://www.youtube.com/watch?v=Nv-ofI9eTiU",
			vurl: "amo40-g11-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/Nv-ofI9eTiU/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 11.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g11-p04",   
            form: "Grade11-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "graphs",
            YTurl: "https://www.youtube.com/watch?v=sXP1nnsLBy4",
			vurl: "amo40-g11-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/sXP1nnsLBy4/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 11.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g11-p05",   
            form: "Grade11-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "topology",
            YTurl: "https://www.youtube.com/watch?v=3ODAF9SC0IQ",
			vurl: "amo40-g11-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/3ODAF9SC0IQ/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 11.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g12-p01",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "inequalities",
            YTurl: "https://www.youtube.com/watch?v=2x9kPeaKJDg",
			vurl: "amo40-g12-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/2x9kPeaKJDg/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 12.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g12-p02",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "triangle-geometry",
            YTurl: "https://www.youtube.com/watch?v=mI4WrwRl5Uk",
			vurl: "amo40-g12-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/mI4WrwRl5Uk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 12.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g12-p03",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "modular-arithmetic",
            YTurl: "https://www.youtube.com/watch?v=NJydU7N5E8M",
			vurl: "amo40-g12-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/NJydU7N5E8M/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 12.kl. 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g12-p04",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "induction",
            YTurl: "https://www.youtube.com/watch?v=6DJBsQoRog0",
			vurl: "amo40-g12-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/6DJBsQoRog0/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 12.kl. 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g12-p05",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "induction",
            YTurl: "https://www.youtube.com/watch?v=bjZc82a83cU",
			vurl: "amo40-g12-p05.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/bjZc82a83cU/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40.AMO, 12.kl. 5.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo40-g05-p01-en",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "English",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "case-analysis",
            YTurl: "https://www.youtube.com/watch?v=FPAlCO560Ok",
			vurl: "amo40-g05-p01-en.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/FPAlCO560Ok/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "40th OpenMO, Grade 5, Problem 1",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo41-g05-p01",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2014",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "proportions",
            YTurl: "https://www.youtube.com/watch?v=UWuWNCKsSwk",
			vurl: "amo41-g05-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/UWuWNCKsSwk/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "41.AMO, 5.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "amo41-g05-p02",   
            form: "Grade5-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2014",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Open Math Olympiad",
            subjects: "proportions",
            YTurl: "https://www.youtube.com/watch?v=9POaCeXqWvo",
			vurl: "amo41-g05-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/9POaCeXqWvo/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "41.AMO, 5.kl. 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "sol61-g12-p01",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2011",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "LV Prep Olympiad in Math",
            subjects: "function-properties",
            YTurl: "https://www.youtube.com/watch?v=KbJdr_5Q-oI",
			vurl: "sol61-g12-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/KbJdr_5Q-oI/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "61.SOL, 12.kl. 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "cgmo12-p01",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "China Girls Mathematical Olympiad",
            subjects: "",
            YTurl: "https://www.youtube.com/watch?v=UNyM7DyFDug",
			vurl: "cgmo12-p01.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/UNyM7DyFDug/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "12. ĶMMO, 1.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "cgmo12-p02",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "China Girls Mathematical Olympiad",
            subjects: "",
            YTurl: "https://www.youtube.com/watch?v=UNyM7DyFDug",
			vurl: "cgmo12-p02.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/UNyM7DyFDug/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "12. ĶMMO, 2.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "cgmo12-p03",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "China Girls Mathematical Olympiad",
            subjects: "",
            YTurl: "https://www.youtube.com/watch?v=UNyM7DyFDug",
			vurl: "cgmo12-p03.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/UNyM7DyFDug/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "12. ĶMMO, 3.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },

{
            type: "Video",
            label: "cgmo12-p04",   
            form: "Grade12-Age13",
            choreographer:  "kalvisapsitis1",
            year:  "2013",
            lesson: "Latvian",
            withChoreographer: "yes",
			camp: "China Girls Mathematical Olympiad",
            subjects: "",
            YTurl: "https://www.youtube.com/watch?v=UNyM7DyFDug",
			vurl: "cgmo12-p04.html", 
            quality: "high",
	        thumbnail:"http://img.youtube.com/vi/UNyM7DyFDug/default.jpg",
            hasVenue: true,
            loc: "Latvia",
	        hebrewName: "12. ĶMMO, 4.uzd.",
	        source: "submitted",
	        submitter:"KA",
	        submitterEmail: "datu.nesejs@gmail.com",
	        note: "...",
	        submitDate: "2014-04-04",
	        upDate: "2014-04-04"
  },]
}